// Export service: PDF & Excel report generation with full Arabic support.
//
// PDF  : pdf + printing packages. Arabic text requires embedding a TTF that
//        contains Arabic glyphs — we use the bundled Tajawal/Cairo fonts
//        (also used by the UI), so exports render identical to the app.
// Excel: `excel` package (xlsx). Arabic strings are natively supported.

import 'dart:io';
import 'dart:typed_data';

import 'package:excel/excel.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart' show DateFormat;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../models/transaction.dart';
import '../utils/helpers.dart';

abstract final class ExportService {
  // ------------------------------------------------------------------ PDF

  /// Builds a branded Arabic PDF report. Returns the generated bytes.
  static Future<Uint8List> generatePdf({
    required List<Transaction> transactions,
    required String title,
    required double totalIncome,
    required double totalExpense,
  }) async {
    final pw.Font arabic = pw.Font.ttf(
      await rootBundle.load('assets/fonts/Tajawal-Regular.ttf'),
    );
    final pw.Font arabicBold = pw.Font.ttf(
      await rootBundle.load('assets/fonts/Tajawal-Bold.ttf'),
    );
    final pw.ThemeData theme = pw.ThemeData.withFont(
      base: arabic,
      bold: arabicBold,
    );

    final pw.Document doc = pw.Document(theme: theme);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        textDirection: pw.TextDirection.rtl, // Arabic RTL PDF
        margin: const pw.EdgeInsets.all(28),
        header: (pw.Context ctx) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(bottom: 12),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: <pw.Widget>[
              pw.Text(
                title,
                style: pw.TextStyle(
                  font: arabicBold,
                  fontSize: 18,
                  color: PdfColor.fromHex('#0F2A54'),
                ),
              ),
              pw.Text(
                'المحاسب الذكي — تقرير مالي (${DateFormat('yyyy/MM/dd').format(DateTime.now())})',
                style: pw.TextStyle(
                  font: arabic,
                  fontSize: 10,
                  color: PdfColor.fromHex('#6B7A99'),
                ),
              ),
              pw.Divider(color: PdfColor.fromHex('#00C896'), thickness: 1.5),
            ],
          ),
        ),
        build: (pw.Context ctx) => <pw.Widget>[
          // ---- Summary cards ----
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: <pw.Widget>[
              _summaryBox('إجمالي الدخل', totalIncome, '#00C896', arabicBold),
              _summaryBox(
                  'إجمالي المصروف', totalExpense, '#E5484D', arabicBold),
              _summaryBox(
                  'الصافي', totalIncome - totalExpense, '#0F2A54', arabicBold),
            ],
          ),
          pw.SizedBox(height: 16),
          // ---- Transactions table ----
          pw.TableHelper.fromTextArray(
            headers: <String>['التاريخ', 'النوع', 'التصنيف', 'الوصف', 'المبلغ'],
            headerStyle: pw.TextStyle(
              font: arabicBold,
              color: PdfColors.white,
              fontSize: 11,
            ),
            headerDecoration: pw.BoxDecoration(
              color: PdfColor.fromHex('#0F2A54'),
            ),
            cellStyle: pw.TextStyle(font: arabic, fontSize: 10),
            cellAlignment: pw.Alignment.centerRight,
            oddRowDecoration:
                pw.BoxDecoration(color: PdfColor.fromHex('#F5F7FB')),
            data: transactions
                .map((Transaction t) => <String>[
                      Helpers.dateShort(t.date),
                      t.type == TxType.income ? 'دخل' : 'مصروف',
                      t.category.arLabel,
                      t.note.isEmpty ? '—' : t.note,
                      Helpers.money(t.amount),
                    ])
                .toList(),
          ),
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _summaryBox(
      String label, double value, String hex, pw.Font bold) {
    return pw.Container(
      width: 160,
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex(hex),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: <pw.Widget>[
          pw.Text(label,
              style: pw.TextStyle(
                  font: bold, fontSize: 10, color: PdfColors.white)),
          pw.SizedBox(height: 4),
          pw.Text(
            value.toStringAsFixed(0),
            style:
                pw.TextStyle(font: bold, fontSize: 16, color: PdfColors.white),
          ),
        ],
      ),
    );
  }

  // ------------------------------------------------------------------ Excel

  /// Builds an .xlsx workbook with one sheet of transactions.
  static Future<Uint8List> generateExcel(List<Transaction> transactions) async {
    final Excel excel = Excel.createExcel();
    final Sheet sheet = excel['التقرير'];

    sheet.appendRow(<TextCellValue>[
      TextCellValue('التاريخ'),
      TextCellValue('النوع'),
      TextCellValue('التصنيف'),
      TextCellValue('الوصف'),
      TextCellValue('المبلغ'),
      TextCellValue('الحالة'),
    ]);

    for (final Transaction t in transactions) {
      sheet.appendRow(<TextCellValue>[
        TextCellValue(Helpers.dateShort(t.date)),
        TextCellValue(t.type == TxType.income ? 'دخل' : 'مصروف'),
        TextCellValue(t.category.arLabel),
        TextCellValue(t.note.isEmpty ? '—' : t.note),
        TextCellValue(t.amount.toStringAsFixed(2)),
        TextCellValue(t.synced ? 'مزامنة' : 'محلي'),
      ]);
    }

    // Remove the default empty "Sheet1".
    final List<String> sheets = excel.sheets.keys.toList();
    for (final String s in sheets) {
      if (s != 'التقرير') excel.rename(s, 'التقرير');
    }
    try {
      excel.delete('Sheet1');
    } catch (_) {}

    final List<int>? bytes = excel.encode();
    return Uint8List.fromList(bytes ?? <int>[]);
  }

  // ------------------------------------------------------------------ Share

  /// Saves bytes to a temp file and opens the Android share sheet.
  static Future<void> shareFile(Uint8List bytes, String fileName) async {
    final Directory dir = await getTemporaryDirectory();
    final String path = '${dir.path}/$fileName';
    await File(path).writeAsBytes(bytes, flush: true);
    await Share.shareXFiles(
      <XFile>[XFile(path)],
      text: 'تقرير المحاسب الذكي 📊',
    );
  }
}
